//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vhudson-jaxb-ri-2.2-147 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.05.09 at 11:30:21 AM PDT 
//


package QuizBuilder;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generated package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generated
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link HealthismQuiz }
     * 
     */
    public HealthismQuiz createHealthismQuiz() {
        return new HealthismQuiz();
    }

    /**
     * Create an instance of {@link HealthismQuiz.Question }
     * 
     */
    public HealthismQuiz.Question createHealthismQuizQuestion() {
        return new HealthismQuiz.Question();
    }

    /**
     * Create an instance of {@link HealthismQuiz.Question.Options }
     * 
     */
    public HealthismQuiz.Question.Options createHealthismQuizQuestionOptions() {
        return new HealthismQuiz.Question.Options();
    }

}
